#  1、YAML基本语法
#    – 使用缩进表示层级关系
#    – 缩进时不允许使用Tab键，只允许使用空格。
#    – 缩进的空格数目不重要，只要相同层级的元素左侧对齐即可
#    – 大小写敏感
#    k:(空格)v来表示一对键值对（空格必须有）；
servier:
  port: 8080
# 激活dev配置文件
spring:
  profiles:
    active: dev